### ISSUE TITLE
Missing references links

### ISSUE THREAD

**Issue by Nowosad** [Nowosad/spData#10]
https://nowosad.github.io/spData/reference/index.html

@Robinlovelace I don't know how to fix it (yet).

**Comment by Robinlovelace** [comment]
I think you just need to write a heading before each entry without any roxygen tags. Looking at stplanr, this was what generated the result below:


![image](https://user-images.githubusercontent.com/1825120/28766913-94ba1e6a-75c9-11e7-857c-5afcfde057cf.png)

```r

#' Convert a bounding box to a SpatialPolygonsDataFrame
#'
#' Takes a bounding box as an input and outputs a box in the form of a polygon
```

I think removing the @description tags and moving the content to the top of each entry may solve this issue.

**Comment by Nowosad** [comment]
Ok, I think, I've fixed it (partially) - https://nowosad.github.io/spData/reference/index.html. 
The bottom value in the .R files should be the name of the dataset (not NULL). 

There are still a few problems (getisord, erie, and boston) - .rda files contan more than one object, so Roxygen2 has some problem with it. 
I'll investigate it a little bit more later.

**Comment by Robinlovelace** [comment]
That looks fine - does not need to be perfect. Great work. Suggest closing as it's 90% fixed.
