### ISSUE TITLE
Prep for the next CRAN submission

### ISSUE THREAD

**Issue by Nowosad** [Nowosad/spData#12]
https://cran.r-project.org/web/checks/check_results_spData.html

Version: 0.2.2
Check: data for non-ASCII characters
Result: NOTE
     Note: found 1 marked UTF-8 string

**Comment by Nowosad** [comment]
I'm unable to reproduce this NOTE:
```R
my_env = c("_R_CHECK_ASCII_DATA_" = TRUE)
devtools::check(env_vars = my_env)
```

**Comment by Robinlovelace** [comment]
This does not sound like a major issue but would be good to know what's going on.

**Comment by Nowosad** [comment]
(We cannot update the CRAN version without resolving this issue)
Probably, there is one element of one of the datasets that have non-ASCII characters. The only problem is that I cannot locate it.

**Comment by Robinlovelace** [comment]
So the mission is to find a way to identify non ASCII characters in an R object. 

Here's a starter for 10 using a function in the **tools** package that may help to identify them:

``` r
library(spData)
library(tidyverse)
#> Loading tidyverse: ggplot2
#> ...
d = data(package = "spData")
class(d)
#> [1] "packageIQR"
df = as_data_frame(d$results)
ds = filter(df, !grepl(pattern = " ", Item)) %>% pull(Item)
obj = get(ds[1])
sapply(obj@data, tools::showNonASCII)
#> 3: NA
```

**Comment by Robinlovelace** [comment]
But not sure how to find out exactly which object is causing the note.

**Comment by Nowosad** [comment]
Fixed - https://github.com/Nowosad/spData/commit/d50ea277ee911fd115f8c68484c068daa282c1f3 (change the name Côte d'Ivoire -> Ivory Coast)

**Comment by Robinlovelace** [comment]
Nice - and well found!
