### ISSUE TITLE
spData lacks projected polygons

### ISSUE THREAD

**Issue by Robinlovelace** [Nowosad/spData#18]
I think it would be useful. Any ideas? somewhere from outside US/UK would be good IMO.

**Comment by Robinlovelace** [comment]
Working on it using data from http://www.stats.govt.nz/browse_for_stats/Maps_and_geography/Geographic-areas/digital-boundary-files.aspx#census

**Comment by Nowosad** [comment]
Have you take a look at existing data in inst/shapes? Naybe there is something projected...

**Comment by Robinlovelace** [comment]
Agree - will be a tiny up-to-date one of nz in sf format is my thinking... Results for Auckland:

```
> auckland <- read_sf(system.file("shapes/auckland.shp", package="spData"))
> plot(aukland)
Error in plot(aukland) : object 'aukland' not found
> plot(auckland)
> st_bbox(auckland)
xmin ymin xmax ymax 
 7.6 -4.3 91.5 99.3 
> st_crs(auckland)
Coordinate Reference System: NA
```

**Comment by Robinlovelace** [comment]
any other ideas?

**Comment by Robinlovelace** [comment]
Pushing it not - looks good and is only 41 KB!

**Comment by Robinlovelace** [comment]
Looking for a projected point dataset now for the subsetting section.

**Comment by Robinlovelace** [comment]
E.g.: https://data.linz.govt.nz/layer/50284-nz-height-points-topo-150k/
