### ISSUE TITLE
Error with spdep

### ISSUE THREAD

**Issue by badassperson** [Nowosad/spData#22]
Hi there, I had this error when trying to install the package hierfstat:
Thank you for any help that you can provide!
-Zach

> install.packages("hierfstat")
ERROR: dependency ‘spData’ is not available for package ‘spdep’
* removing ‘/home/zachary/R/x86_64-pc-linux-gnu-library/3.2/spdep’
ERROR: dependency ‘spdep’ is not available for package ‘adegenet’
* removing ‘/home/zachary/R/x86_64-pc-linux-gnu-library/3.2/adegenet’
ERROR: dependency ‘adegenet’ is not available for package ‘hierfstat’
* removing ‘/home/zachary/R/x86_64-pc-linux-gnu-library/3.2/hierfstat’

The downloaded source packages are in
	‘/tmp/RtmpoO49FT/downloaded_packages’
Warning messages:
1: In install.packages("hierfstat") :
  installation of package ‘spdep’ had non-zero exit status
2: In install.packages("hierfstat") :
  installation of package ‘adegenet’ had non-zero exit status
3: In install.packages("hierfstat") :
  installation of package ‘hierfstat’ had non-zero exit status

----
> R.Version()
$platform
[1] "x86_64-pc-linux-gnu"

$arch
[1] "x86_64"

$os
[1] "linux-gnu"

$system
[1] "x86_64, linux-gnu"

$status
[1] ""

$major
[1] "3"

$minor
[1] "2.3"

$year
[1] "2015"

$month
[1] "12"

$day
[1] "10"

$`svn rev`
[1] "69752"

$language
[1] "R"

$version.string
[1] "R version 3.2.3 (2015-12-10)"

$nickname
[1] "Wooden Christmas-Tree"

**Comment by Nowosad** [comment]
Hi Zach, have you tried to install **spData**, and **hierfstat** afterwards?

```
install.packages("spData")
install.packages("hierfstat")
```

Is is solve the problem?

**Comment by badassperson** [comment]
Nope... 

> install.packages("spData")
Installing package into ‘/home/zachary/R/x86_64-pc-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
Warning message:
package ‘spData’ is not available (for R version 3.2.3) 
> install.packages("hierfstat")

.
.
.

ERROR: dependency ‘spData’ is not available for package ‘spdep’
* removing ‘/home/zachary/R/x86_64-pc-linux-gnu-library/3.2/spdep’
ERROR: dependency ‘spdep’ is not available for package ‘adegenet’
* removing ‘/home/zachary/R/x86_64-pc-linux-gnu-library/3.2/adegenet’
ERROR: dependency ‘adegenet’ is not available for package ‘hierfstat’
* removing ‘/home/zachary/R/x86_64-pc-linux-gnu-library/3.2/hierfstat’

The downloaded source packages are in
	‘/tmp/RtmpqImuwz/downloaded_packages’
Warning messages:
1: In install.packages("hierfstat") :
  installation of package ‘spdep’ had non-zero exit status
2: In install.packages("hierfstat") :
  installation of package ‘adegenet’ had non-zero exit status
3: In install.packages("hierfstat") :
  installation of package ‘hierfstat’ had non-zero exit status

**Comment by Nowosad** [comment]
Ok, I see where is the problem. Your R version is outdated (3.2.3 was released almost two years ago). Install new version of R and it should work.

**Comment by badassperson** [comment]
Thank you so much Nowosad-- I really appreciate the help!

-z

**Comment by dchiu911** [comment]
Hi @Nowosad is it possible to roll back to `R (>= 3.2)`?

**Comment by Nowosad** [comment]
Hi @dchiu911 - no, it is not. Many of our objects has the `sf` class, therefore we decided to keep the same required version as the **sf** package...
