### ISSUE TITLE
don't globally modify repos option with repository that lacks windows/mac binaries

### ISSUE THREAD

**Issue by richfitz** [Nowosad/spData#24]
This line - https://github.com/Nowosad/spData/blob/master/R/zzz.R#L7 sets `repos` and I see issues on user's windows machines because the corresponding drat repository does not include windows binaries (or dummy PACKAGES files) for 3.3 or 3.4: https://github.com/Nowosad/drat/tree/gh-pages/bin

```
> library(spData)
To access larger datasets in this package, install the spDataLarge
package with: `install.packages('spDataLarge')`
> getOption("repos")
                                                        nowosaddrat 
       "https://cran.rstudio.com" "https://nowosad.github.io/drat/" 
> install.packages("ape")
Warning: unable to access index for repository https://nowosad.github.io/drat/bin/macosx/el-capitan/contrib/3.4:
  cannot open URL 'https://nowosad.github.io/drat/bin/macosx/el-capitan/contrib/3.4/PACKAGES'
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/ape_5.0.tgz'
Content type 'application/x-gzip' length 1772789 bytes (1.7 MB)
==================================================
downloaded 1.7 MB


The downloaded binary packages are in
    /var/folders/3z/86tv450j7kb4w5y4wpxj6d5r0000gn/T//RtmpbbuYo7/downloaded_packages
```

**Comment by Robinlovelace** [comment]
Thanks for the input - that may help explain why some people had issues using examples from spDataLarge. I guess we need to build Windows/Mac binaries. Not this was briefly discussed here: https://github.com/Robinlovelace/geocompr/issues/126

There are other ways to install data packages that don't fit on CRAN I know and if you have any suggestions they'll be appreciated - this is how we currently ask people to do it: 

http://geocompr.robinlovelace.net/spatial-class.html#prerequisites

**Comment by richfitz** [comment]
You don't have to actually create binaries - just the structure that CRAN assumes - for example: https://github.com/mrc-ide/drat/tree/master/bin/windows/contrib/3.4

An empty PACKAGE file with each of the major releases is sufficient (I'm not 100% sure if the gzipped empty file is compulsory but I have added it to mine for ages and it seems to work - the new PACKAGES.rds file definitely is optional).

Adding these directories should be a lot easier than actually building binaries.

Large data on CRAN is such a complete pain - especially because caching solutions easily fall foul of CRAN policies of writing to disk.  I had a shot at some of this a while ago (experiments in an unfinished package called datastorr) but it's still something I don't know how to do nicely.  I wish that their size restrictions weren't so punitive - 23MB is pretty tiny these days.

**Comment by Nowosad** [comment]
Hi @richfitz - thanks for the information. 
I'll try to fix it tomorrow.

**Comment by Nowosad** [comment]
@richfitz @Robinlovelace 
https://github.com/Nowosad/drat/commit/28eb05288c8697c6aaf04c12f99876bba547cf50 - I added empty PACKAGE and PACKAGE.gz files for windows and macos binaries.

**Comment by richfitz** [comment]
Great, thanks so much :tada

**Comment by Nowosad** [comment]
Than
