### ISSUE TITLE
Problem with examples using **spdep** on the pkgdown website

### ISSUE THREAD

**Issue by Nowosad** [Nowosad/spData#31]
![screenshot from 2019-01-26 16-22-28](https://user-images.githubusercontent.com/3457131/51789196-9c1d2200-2186-11e9-9dfa-0c0ac0dc2214.png)

Temporary solution: Don't run any examples on the pkgdown website:

```r
pkgdown::build_site(examples = FALSE)
```

**Comment by Robinlovelace** [comment]
Strange. Not sure why it thinks **spData** isn't installed...
