### ISSUE TITLE
Error to install SPDEP on Amazon EC2

### ISSUE THREAD

**Issue by henokfasil** [Nowosad/spData#32]
I set up Rstudio on AmazonEC2. I am connected to the instance via PuTTY. To install packages like spdep, readtxt, splm, and dplyr.

I have tried through PuTTY

sudo -s 
sudo yum install spdep
However, I have this Error

Loaded plugins: priorities, update-motd, upgrade-helper
No package spdep available.

**Comment by Nowosad** [comment]
@henokfasil issues related to the **spdep** package should be posted at https://github.com/r-spatial/spdep/issues.

Btw Have you tried to install this package inside R:

```r
install.packages("spdep")
```
