### ISSUE TITLE
Missing iso_a2 info in 'world'

### ISSUE THREAD

**Issue by etabeta78** [Nowosad/spData#33]
`world` data set is missing a few ISO alpha-2 codes (e.g. France and Norway).
this causes incomplete subsets in some situations, e.g. when I'd like to drop a country by checking its ISO code:

`world[which(world$continent=="Europe" & world$iso_a2 != "IT"),]`

**Comment by Robinlovelace** [comment]
Interesting. The subsetting works for me but I can see the NAs.
Please see below. Do you know what the codes should be (I took a guess!)?

``` r
library(sf)
#> Linking to GEOS 3.7.0, GDAL 2.4.0, PROJ 5.2.0
library(spData)
sel_na = which(is.na(spData::world$iso_a2))
world$name_long[sel_na]
#> [1] "Norway"          "France"          "Northern Cyprus" "Somaliland"

# is this right??
world$name_long[sel_na] = c("NO", "FR", "NC", "SO")

summary(spData::world$iso_a2 == "US")
#>    Mode   FALSE    TRUE    NA's 
#> logical     172       1       4
summary(spData::world$iso_a2 == "IT")
#>    Mode   FALSE    TRUE    NA's 
#> logical     172       1       4
it_n = world[which(world$continent=="Europe" & world$iso_a2 != "IT"),]
it_y = world[which(world$continent=="Europe" & world$iso_a2 == "IT"),]
plot(it_y)
```

![](https://i.imgur.com/radnJM9.png)

``` r
plot(it_n)
```

![](https://i.imgur.com/16wHnyC.png)

<sup>Created on 2019-03-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by etabeta78** [comment]
If you compare the it_n plot with the complete plot of Europe, you'll see that France and Norway have not been drawn because they are not included in the subset it_n (the condition in the which returns NA for those rows and therefore they are not included).

**Comment by Nowosad** [comment]
Hi @etabeta78 - I was aware of this before, however (I do not remember why) I decided not to act on it... I need to check this and will let you know if a few days...

**Comment by Nowosad** [comment]
@etabeta78 thanks for opening the issue. I've added the codes for Norway and France - https://github.com/Nowosad/spData/commit/db151b5b1a6d1bad2b3ed6c527c2857229d5ff3a. You can now try the development version of the package: `devtools::install_github("nowosad/spData")`.

**Comment by Robinlovelace** [comment]
Great fix @Nowosad.

Where is the code that generates the underlying data? Just looked in `?spData::world`.

**Comment by Nowosad** [comment]
It is here - https://github.com/Robinlovelace/geocompr/blob/be44062c023c42ae6ecf0d5555c158e9896b2c63/code/download-data.R#L32

Should I move it somewhere else, @Robinlovelace ?

**Comment by Robinlovelace** [comment]
I think the best practice place for it to be is in a `data-raw` folder, e.g.: https://github.com/ropensci/stats19/tree/master/data-raw. A link to that script would also be an option but I think the `data-raw` folder is best, so it lives in the pkg repo. Thanks for digging it out!

**Comment by etabeta78** [comment]
Sorry for not getting back earlier on this, but it's been a busy week.
Thanks a lot for the prompt support.

**Comment by Nowosad** [comment]
Ok, the code is in the repo now - https://github.com/Nowosad/spData/blob/master/data-raw/world.R

**Comment by Robinlovelace** [comment]
Awesome work @Nowosad many thanks.
