### ISSUE TITLE
Incorrect country borders in 'world'

### ISSUE THREAD

**Issue by lifegivesyoulemons** [Nowosad/spData#34]
For some undisclosed reason, the Crimea region is a part of Russian Federation in 'world', while in fact, it belongs to Ukraine.
![image](https://user-images.githubusercontent.com/35201079/63276039-47203500-c2ab-11e9-8f30-708bd39964bf.png)

**Comment by Nowosad** [comment]
@lifegivesyoulemons - the `world` object is based on the data provided by https://www.naturalearthdata.com/. You can ask there about it.
