### ISSUE TITLE
CRAN packages with datasets requiring other packages

### ISSUE THREAD

**Issue by Nowosad** [Nowosad/spData#36]
@rsbivand @Robinlovelace,
we have got an email from CRAN (see it below).
Our logs are at https://www.stats.ox.ac.uk/pub/bdr/noSuggests/spData.out. 
We need to decide if we want to (1) import **sp** and **raster** or (2) use .R wrappers. 
The second approach of the **Matrix** package can be seen at https://github.com/cran/Matrix/tree/master/data. 

> See the logs (and README.txt) at
> https://www.stats.ox.ac.uk/pub/bdr/noSuggests/ .
> 
> At least one of the datasets cannot be loaded without a package declared
> in Suggests: -- typically this is because it loads a namespace defining
> S4 classes, and such imports should be declared in Imports or (as Matrix
> does) use a .R wrapper.  For example if I do
> 
> data('Sample_ID_data', package = 'DDPNA')
> str(Sample_ID_data)
> 
> namespaces
> 
> BiocGenerics Biostrings IRanges S4Vectors XVector crayon zlibbioc
> 
> get loaded, pulled in by Biostrings so the latter has to be available.
> 
> Please correct ASAP and before Feb 20 to safely retain the package on CRAN.

**Comment by Robinlovelace** [comment]
First impression is that 2) looks best in terms of reducing dependencies although happy to defer to majority vote.

**Comment by rsbivand** [comment]
Note that for **sp**, 2) may run foul of copying `comment` additions to `CRS`, `SpatialPolygons` and `Polygons` objects, which will need to be handled/checked separately. There will also be problems with S4 objects nested in S4 objects. You'd have to experiment.

**Comment by Nowosad** [comment]
Sadly, I do not have time in the near future to try to implement the second approach. For now, I made a PR using the first approach - https://github.com/Nowosad/spData/pull/37/files. Please take a look and let me know if you are ok with it.

**Comment by Nowosad** [comment]
New version is on CRAN (https://cran.r-project.org/web/packages/spData/index.html).
