### ISSUE TITLE
spdata stack usage issue for some macs

### ISSUE THREAD

**Issue by Makosak** [Nowosad/spData#43]
I'm using the spData package with the geocomp text for a class I'm teaching, and several student (at least 5) are running into issues using spData on their Mac OS systems. They get the error: "C stack usage 7969648 is too close to the limit" --> and after troubleshooting can only get rid of the error when using a different library (spDatalarge is okay), using their own data, or running from the RStudio cloud environment. They've cleared their workspace several times, increased stack size to 65532 (which appears to be the limit) and even reinstalled RStudio. My students didn't have this issue when we used the text last year or even last quarter, and again it seems to only occur when using spData. Were there any changes in the last few months that could trigger a size limitation issue? We want to use the gecomp textbook so hope we can resolve.

**Comment by Robinlovelace** [comment]
Thanks for raising the issue. It's a tricky one and similar to an issue that I was having when testing shiny apps, documented here for the hosting service shinyapps.io: https://community.rstudio.com/t/error-when-deploying-r-shiny-app-error-c-stack-usage-7969860-is-too-close-to-the-limit/13427/3

Unfortunately I never fully understood what was going on, although I gather that the issue refers to the level of recursion going on: https://stackoverflow.com/questions/14719349/error-c-stack-usage-is-too-close-to-the-limit

I have no idea how `spData` causes this issue as it's not supposed to run code, just provide data, so this issue may be hard to debug. To help diagnose the precise cause of the issue more information could help. Was it when the package was loaded or first installed that the error messages appeared? Or was it when using a particular dataset?

**Comment by Makosak** [comment]
It seemed to occur when they were working with the "world" dataset specifically. I've asked the students to post here, so hopefully they will shortly. :) 

I can have them download data required directly from this repo as an interim solution. Agreed, this is a very odd "bug" to have as just loading data from a package shouldn't do this. Hopefully we can resolve soon!

**Comment by Nowosad** [comment]
Hi @Makosak, thanks for opening the issue. I think this issue is related to the recent changes in the **sf** package. Now, **sf** uses a different representation of spatial projections (https://www.r-spatial.org/r/2020/03/17/wkt.html). 
Objects of **sf** class in the **spData** had been using the old representation until last week (https://github.com/Nowosad/spData/issues/41).

I assume the issue your students have is due to having an older version of **sf** than 0.9.
I do not know what is the best approach to fix it, however, for now, you can try to download the older version of **spData** with:

```
remotes::install_github("nowosad/spData@v0.34")
```

**Comment by spaykin** [comment]
Hi @Nowosad, I'm one of the student's in @Makosak's geocomp class. Reinstalling the older version of spData resolved the issue! Outside of this I was still running into the error described above. Luckily installing the older version seemed to work. Thanks.
