### ISSUE TITLE
Port data from RQGIS

### ISSUE THREAD

**Issue by Robinlovelace** [Nowosad/spData#45]
See https://github.com/Robinlovelace/geocompr/issues/519

Could also go in spDataLarge if too big. Thoughts @Nowosad ?

**Comment by Nowosad** [comment]
Makes sense. Can you prepare a list of objects with their classes and sizes?

**Comment by Robinlovelace** [comment]
Sure. I think they could all fit:

```
ls -hal RQGIS/data/*
-rw-rw-r-- 1 robin robin 2.4K Apr 21 09:35 data/comm.rda
-rw-rw-r-- 1 robin robin  11K Apr 21 09:35 data/dem.rda
-rw-rw-r-- 1 robin robin 100K Apr 21 09:35 data/ndvi.rda
-rw-rw-r-- 1 robin robin 2.5K Apr 21 09:35 data/random_points.rda
-rw-rw-r-- 1 robin robin 1.5K Apr 21 09:35 data/study_area.rda
```

**Comment by Nowosad** [comment]
1. It would be good to check if all of these are used in the book.
2. I think they could find their home in **spDataLarge**. However, maybe it would be good to change names of some of them...
