### ISSUE TITLE
CRAN issues

### ISSUE THREAD

**Issue by Nowosad** [Nowosad/spData#49]
```
  Found the following (possibly) invalid URLs:
    URL: http://www.math.yorku.ca/SCS/Gallery/bright-ideas.html
      From: man/state.vbm.Rd
      Status: 403
      Message: Forbidden
    URL: https://cyclehireapp.com/cyclehirelive/cyclehire.csv
      From: man/cycle_hire.Rd
      Status: Error
      Message: libcurl error code 7:
        	Failed to connect to cyclehireapp.com port 443: Connection refused
```

@rsbivand should I remove the http://www.math.yorku.ca/SCS/Gallery/bright-ideas.html url from the data documentation or replace it with some other link?
@Robinlovelace is there any alternative link to https://cyclehireapp.com/cyclehirelive/cyclehire.csv?

**Comment by rsbivand** [comment]
Seems to have moved to http://euclid.psych.yorku.ca/SCS/Gallery/bright-ideas.html

**Comment by Nowosad** [comment]
@Robinlovelace do you know of any alternative link to https://cyclehireapp.com/cyclehirelive/cyclehire.csv?

**Comment by Robinlovelace** [comment]
Good question, how is this @Nowosad ?

https://data.gov.uk/dataset/a1db6899-75c4-4f12-bf98-7ec2aafd3135/london-cycle-hire-stations

**Comment by Nowosad** [comment]
Great, thanks!

**Comment by Robinlovelace** [comment]
Great work :tada:
