### ISSUE TITLE
Improper map of Ukraine

### ISSUE THREAD

**Issue by rshopa** [Nowosad/spData#50]
I must report that ```spDataLarge``` uses improper maps showing Ukrainian Crimea as Russian. If this package is designed to be utilised on international scale, the borders should be shown as recognised by UN.

```
> ukr <- world[world$name_long == "Ukraine", ]
> msk <- world[world$name_long == "Russian Federation", ]
> plot(st_geometry(ukr), col = "gray", lwd = 3)
> plot(st_geometry(msk), col = "gray", lwd = 3)
```
![image](https://user-images.githubusercontent.com/15617645/90875826-6401b380-e3aa-11ea-981b-8b3560a6a66d.png)
![image](https://user-images.githubusercontent.com/15617645/90875699-3fa5d700-e3aa-11ea-9fac-47bfaf94c620.png)

If no correction is made, I shall report this issue on higher level and make viral.

**Comment by Nowosad** [comment]
@Natalilab I believe that we actually made some changes in **spData**:

```r
library(spData)
mapview::mapview(world)
```

![image](https://github.com/user-attachments/assets/d050f838-3eab-4840-9e3e-aea5550a904d)
