### ISSUE TITLE
Source of base layer of world map?

### ISSUE THREAD

**Issue by jejimel** [Nowosad/spData#53]
Hi there, 

I used the world data in spData to make maps for a journal article (super easy to use thanks!). The journal has asked us to provide a direct link to the base layer of the map used in the legend of the maps. I'll put a sentence that the maps, I made the maps using spData. But I was wondering if you might also be able to share the website where the base layer came from (e.g., usgs.gov). I couldn't find this in the package info. 

Thanks! 

Lily

**Comment by Nowosad** [comment]
Hi Lily,
the world map was downloaded from https://www.naturalearthdata.com/ using the **rnaturalearth** package.

**Comment by Robinlovelace** [comment]
Hi @jejimel, the world object comes from the Natural Earth open data repository, as Jakub says (he replied while I was typing this, hence kind of duplicate reply!). This is documented in the help page, accessible from R by typing `?world`. See here also: https://nowosad.github.io/spData/reference/world.html.

**Comment by jejimel** [comment]
Thanks!
