### ISSUE TITLE
CRAN Package Checks

### ISSUE THREAD

**Issue by Nowosad** [Nowosad/spData#58]
> Dear maintainer,
> 
> Please see the problems shown on
> [<https://cran.r-project.org/web/checks/check_results_spData.html>](https://cran.r-project.org/web/checks/check_results_spData.html).
> 
> In particular, please see the "Found the following HTML validation
> problems" NOTEs in the "HTML version of manual" check for at least some
> of the r-devel checks results.  
> 
> R 4.2.0 switched to use HTML5 for documentation pages.  Now validation
> using HTML Tidy finds problems in the HTML generated from your Rd
> files.  
> 
> To fix, in most cases it suffices to re-generate the Rd files using the
> current CRAN version of roxygen2.  To check whether this already fixes
> things, or whether additional changes you made fixed the problems (e.g.,
> if the problem is from yourself directly generating HTML output), you
> can grab HTML Tidy version 5.8.0 binaries from
> [<https://binaries.html-tidy.org/>](https://binaries.html-tidy.org/) and, with FOO.Rd an Rd file for which
> problems were found, run
> 
>   R CMD Rdconv -t html /path/to/FOO.Rd -o FOO.html
>   tidy -qe --drop-empty-elements no FOO.html
> 
> (Alternatively, you can use R CMD check --as-cran using a current
> version of R-devel.)
> 
> Can you please fix as necessary?
> 
> Please correct before 2022-09-09 to safely retain your package on CRAN.

**Comment by Nowosad** [comment]
Dear @rsbivand, can you take a look at these issues?

**Comment by Robinlovelace** [comment]
Could this help? https://github.com/DavisVaughan/extrachecks-html5

**Comment by rsbivand** [comment]
I'm already in Lucca, and have a new laptop without the tools I'd need. I'll try, but before Monday will be very difficult.

**Comment by rsbivand** [comment]
[00check.log](https://github.com/Nowosad/spData/files/9410668/00check.log) after merge and pull from upstream.

**Comment by Nowosad** [comment]
@rsbivand -- I just submitted the current version of {spData} to CRAN.

**Comment by Nowosad** [comment]
The submission showed 2/3 Notes (depending on the operating system; see https://win-builder.r-project.org/incoming_pretest/spData_2.2.0_20220824_093752/). I think they do not indicate any issues, so I emailed the CRAN team 6 days ago. However, I did not get any reply (yet).

**Comment by rsbivand** [comment]
Maybe ping them again? I can see it in https://cran.r-project.org/incoming/archive/

**Comment by Nowosad** [comment]
Done.

**Comment by Nowosad** [comment]
The new version is now on CRAN -- https://cran.r-project.org/package=spData
