### ISSUE TITLE
Briefly compare spData to alternate map library packages in README?

### ISSUE THREAD

**Issue by cboettig** [Nowosad/spData#6]
It would be great if the readme/DESCRIPTION could briefly compare spData package to other R packages providing map polygons. Or more generally, what motivated you to create this package? Is it just meant as a one-stop-shop for datasets in the http://robinlovelace.net/geocompr text?  Other than object class format used, how do these differ / what is the original source for the datasets? e.g. is `world` here identical to the maps `world` map?

**Comment by Nowosad** [comment]
Hi @cboettig, thanks for your good ideas.
Now, our plan (@Robinlovelace and I) is to fix some minor issues and submit this package to CRAN.
After that we would like to put this package through  the rOpenSci's package review process to make it better. Then, we would certainly try to add these information in the README or DESCRIPTION.

**Comment by Robinlovelace** [comment]
The history of the package explains some of this. It contains spatial datasets collated by @rsbivand for teaching. The fact it has multiple file formats means its useful for benchmarking.

Regarding the `world` dataset, it's actually the same as that provided by **rnaturalearth**. Why duplicate that information? To have in multiple formats a small, fun but globally relevant dataset that everyone can relate to in multiple file formats for benchmarking.

I plan to put in a PR explaining some of this - thanks loads for the suggestion.

**Comment by Nowosad** [comment]
Actually, the geometry of the `world` object is the same as provided by **rnaturalearth**. However, some columns were removed and a few new were added from World Bank (pop, lifeExp, gdpPercap).
