### ISSUE TITLE
Switch to geoBoundaries for `world` dataset

### ISSUE THREAD

**Issue by Robinlovelace** [Nowosad/spData#64]
As shown below the content is different: 

![image](https://github.com/Nowosad/spData/assets/1825120/bee492bf-89fb-42a2-86e5-38537780feaf)

Source: https://www.geoboundaries.org/geoContrast.html?country=UKR&mainSource=geoBoundaries+%28Open%29&comparisonSource=Natural+Earth+v5.0.1&mainLevel=1&comparisonLevel=1

Related: https://github.com/Nowosad/spData/issues/50

**Comment by Nowosad** [comment]
My thoughts:

1. geoboundaries has different countries included, different variables, etc. I am slightly afraid of side-effects of such change.
2. alternative approach can be seen here -- https://observablehq.com/@visionscarto/world-atlas-topojson. I've tried to use it in R, but sadly it's topology is broken (for both s2 and geos)

**Comment by Robinlovelace** [comment]
> geoboundaries has different countries included, different variables, etc. I am slightly afraid of side-effects of such change.

Plan: keep all original `world` column names and change as little as possible.

**Comment by Nowosad** [comment]
@Robinlovelace: the most basic approach could be just to update the borders by hand (e.g., in QGIS). This would keep all of the rest of the data intact.

**Comment by Robinlovelace** [comment]
@Nowosad I'll give it a go.

**Comment by Robinlovelace** [comment]
Progress on this:

![image](https://github.com/Nowosad/spData/assets/1825120/25570d6f-faa0-4dba-9e56-f870316bba65)

**Comment by Robinlovelace** [comment]
Progress...

**Comment by Robinlovelace** [comment]
Looking good.

![image](https://github.com/Nowosad/spData/assets/1825120/eb1f4909-fecd-4bd0-a6c9-cc092d446cc4)

**Comment by Robinlovelace** [comment]
:tada: 

![image](https://github.com/Nowosad/spData/assets/1825120/02fb510e-2bb3-4103-8825-ff316f9b8a70)
