### ISSUE TITLE
Inaccuracy in country polygons which cross 180th meridian in `world` dataset

### ISSUE THREAD

**Issue by HRodenhizer** [Nowosad/spData#67]
Thanks to some help over on [SO](https://stackoverflow.com/questions/76979688/dissolve-internal-boundaries-of-multipolygon-that-crosses-180th-meridian), I discovered some slight offsets between portions of MULTIPOLYGONs that cross the 180th meridian in the `world` dataset.

It looks like this is an issue for Russia, Fiji, and Antarctica.

```r
library(sf)
library(spData)
library(dplyr)
library(ggplot)

meridian_180 <- tibble(lon = c(-180,-180),
                       lat = c(-90, 90)) %>%
  st_as_sf(coords = c("lon","lat"),
           crs = "EPSG:4326") %>%
  summarise(geometry = st_combine(geometry)) %>%
  st_cast("LINESTRING") %>% 
  smoothr::densify(max_distance = 1)


world_180 <- world %>%
  slice(st_intersects(., meridian_180, sparse = FALSE) %>%
          as_vector() %>%
          which())

fiji = world_180$geom[1]
russia = world_180$geom[2]
antarctica = world_180$geom[3]
st_distance(st_cast(fiji, 'POLYGON')[c(1, 3)])
```
![image](https://github.com/Nowosad/spData/assets/38510539/b2fcc64c-9668-4fee-bd06-84fe86770dba)

```r
st_distance(st_cast(russia, 'POLYGON')[c(1, 6)])
```
![image](https://github.com/Nowosad/spData/assets/38510539/4b052596-013c-4094-a129-ba754d5da0e7)

```r
antarctica <- antarctica %>%
  st_transform(crs = 'EPSG:3412')

ggplot(antarctica) +
  geom_sf()
```
![image](https://github.com/Nowosad/spData/assets/38510539/743653fc-306b-483a-8ce2-66d191a04c93)

**Comment by Nowosad** [comment]
Hi @HRodenhizer that was done on purpose (to avoid some invalid geometry problems with s2).

**Comment by Nowosad** [comment]
(Also, importantly datasets from spData are mostly suitable for teaching, benchmarking and testing; I would not suggest using them for research)

**Comment by HRodenhizer** [comment]
Got it - that makes sense. I find that this dataset is extremely useful for low-detail, large extent visualizations, but thanks for the warning!

**Comment by Nowosad** [comment]
Context: https://github.com/r-spatial/sf/issues/1649#issuecomment-859489794
