### ISSUE TITLE
The Stages of Datasets Recovery

### ISSUE THREAD

**Issue by Nowosad** [Nowosad/spData#9]
### `sf`

- [x] `baltimore` - House sales prices, Baltimore, MD 1978
- [x] `cycle_hire` - Cycle hire points in London
- [x] `cycle_hire_osm` - Cycle hire points in London from OSM
- [x] `lnd` - The boroughs of London
- [x] `us_states` - US states polygons
- [x] `world` - World country polygons
- [x] `wheat` - Mercer and Hall wheat yield data

### `sp`

- [x] `auckland` - Marshall's infant mortality in Auckland dataset
- [x] `elect80` - 1980 Presidential election results
- [x] `house` - Lucas county OH housing
- [x] `SplashDams` - Data for Splash Dams in western Oregon
- [x] `state.vbm` - US State Visibility Based Map

### `spdep`

- [x] `afcon` - Spatial patterns of conflict in Africa 1966-1978
- [x] `boston` - Boston Housing Data
- [x] `columbus` - Columbus OH spatial analysis data set
- [x] `eire` - Eire data sets
- [x] `nc.sids` - North Carolina SIDS data
- [x] `NY_data` - New York leukemia data
- [x] `used.cars` - US 1960 used car prices

### misc

- [x] `getisord` - Getis-Ord remote sensing example data
- [x] `hopkins` - Hopkins burnt savanna herb remains
- [x] `huddersfield` - Prevalence of respiratory symptoms
- [x] `jenks71` - Illinois 1959 county gross farm product value per acre
- [x] `us_states_df` - Selected American Community Survey (ACS) data
- [x] `worldbank_df` - Selected World Bank data

**Comment by Robinlovelace** [comment]
Nice. I agree with this list.

**Comment by Nowosad** [comment]
Done
